FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY services/*/package.json services/*/package.json ./services/

RUN npm ci

COPY . .

RUN npm run build --workspaces

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app /app

ARG SERVICE
ENV NODE_ENV=production

WORKDIR /app/services/${SERVICE}

CMD ["node", "dist/index.js"]
